name: Claude Auto Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write

    steps:
      - name: Check for @claude mention in PR
        id: check_claude
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber
            });

            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: prNumber
            });

            const hasClaudeMention = [pr.data.body, ...comments.data.map(c => c.body)]
              .some(body => body && body.includes('@claude'));

            core.setOutput("run_review", hasClaudeMention);

      - name: Checkout repository
        if: steps.check_claude.outputs.run_review == 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Automatic PR Review
        if: steps.check_claude.outputs.run_review == 'true'
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
          direct_prompt: |
            Please review this pull request and provide comprehensive feedback.

            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security implications
            - Test coverage
            - Documentation updates if needed
            - Whether the implementation meets the requirements

            Provide constructive feedback with specific suggestions for improvement.
            Use inline comments to highlight specific areas of concern.

            Please write the review in **Japanese**.
