name: Type Checking

env:
  PYTHON_VERSION: 3.12
  TY_VERSION: 0.0.1a8

on:
  push:

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Install Ty
        run: uv add "ty==${{ env.TY_VERSION }}"

      - name: Run Ruff
        run: uv run ty check
